"use strict";
// ═══════════════════════════════════════
// 吃 · Language Toggle — EN / ZH
// ═══════════════════════════════════════

window.currentLang = 'en';

var TRANSLATIONS = {
  en: {
    'modal-title': 'Before you read — listen',
    'modal-body': 'This web documentary has a soundtrack.<br>Eight voices, recorded in Mandarin.<br><em>Let it run underneath as you explore.</em>',
    'modal-play-label': 'Play the voices',
    'modal-skip': 'Continue in silence→',
    'audio-label': '吃 · Eight voices · Mandarin',
    'cover-en': 'Eating Alone Together',
    'cover-q': 'For Chinese international students in the U.S., how does food function as a way of maintaining cultural identity and navigating belonging?',
    'cover-scroll': 'Scroll to begin',
    'eyebrow-project': 'The Project',
    'pull-rd1': 'When you cross a border,<br>your body doesn\'t forget.<br>It keeps <em>reaching</em> for something.',
    'intro-p1': 'Eight Chinese international students. Eight universities across America — from Atlanta to Boston, Los Angeles to Ithaca. Eight kitchens photographed, eight voices recorded in Mandarin. The question was deceptively simple: <em>what do you eat?</em>',
    'intro-p2': 'What emerged was far more complicated than appetite. Food is where identity gets negotiated daily — quietly, practically, hungrily. Every grocery run is a small act of self-preservation. Every meal cooked alone is a rehearsal of who you were, and a decision about who you\'re becoming.',
    'intro-p3': 'This is not a story about restaurants. It is a story about the space between the stove and the self.',
    'intro-p4': 'The people interviewed will be known here only by the city where they are and the dish they cannot stop missing.',
    'dq1-text': '"Eating is the most important thing in the world. Especially when you\'re sick — the body still wants Chinese food. That instinct doesn\'t negotiate."',
    'dq1-cite': 'Boston · MIT · 5 years in the US',
    'dq2-text': '"I had no car. No delivery. The Chinese food nearby couldn\'t satisfy my craving. That time was <em style="color:var(--ember);font-style:normal">痛苦</em> — real suffering."',
    'dq2-cite': 'Charlottesville · formerly Minnesota · 5 years',
    'dq3-text': '"I ordered 夫妻肺片 and they added 麻酱. It\'s a small thing. But the kind of wrong that accumulates."',
    'dq3-cite': 'Ithaca · 6 years in the US',
    'dq4-text': '"When I\'ve been eating 白人饭 too long, I cook. It\'s like recalibrating. And if I can recreate a taste from home — that\'s something to be proud of."',
    'dq4-cite': 'Atlanta · 2 years in the US',
    'eyebrow-introducing': 'Introducing',
    'eight-title': 'Eight Cities. Eight Dishes. Eight Kitchens.',
    'eight-sub': 'Click to explore.',
    'p-open': 'Open →',
    'p-city-la': 'Los Angeles · 5 years',
    'p-city-boston': 'Boston · 5 years',
    'p-city-atlanta-e': 'Atlanta · 9 years',
    'p-city-atlanta-gt1': 'Atlanta · 1 year',
    'p-city-ithaca': 'Ithaca · 6 years',
    'p-city-cville': 'Charlottesville · 5 years',
    'p-city-atlanta-gt2': 'Atlanta · 2 years',
    'p-city-atlanta-gt3': 'Atlanta · 5 years',
    'p-dish-en-la': 'Intestine & Tofu Fish',
    'p-dish-en-boston': 'Sweet & Sour Pork Ribs',
    'p-dish-en-atlanta-e': 'Lanzhou Pulled Noodles',
    'p-dish-en-atlanta-gt1': 'Chaoshan Beef Hot Pot',
    'p-dish-en-ithaca': 'Husband & Wife Sliced Beef',
    'p-dish-en-cville': "Xi'an Cold Skin Noodles",
    'p-dish-en-atlanta-gt2': 'Dry-Fried Chili Chicken',
    'p-dish-en-atlanta-gt3': 'Fermented Mandarin Fish',
    'p-quote-la': '"Eating together — that\'s already the happiest experience, even if what we made could barely be called Chinese food."',
    'p-quote-boston': '"When sick, the body still wants Chinese food. That instinct doesn\'t negotiate."',
    'p-quote-atlanta-e': '"Half my life has been here. But my tastes haven\'t changed."',
    'p-quote-atlanta-gt1': '"Every meal is Chinese food. Every day I cook for myself."',
    'p-quote-ithaca': '"The happiest meal — not because it was great, but because we were all there."',
    'p-quote-cville': '"In Minnesota — no car, no delivery. That period was 痛苦. Real suffering."',
    'p-quote-atlanta-gt2': '"When I\'ve been eating 白人饭 too long, I cook. It\'s like recalibrating."',
    'p-quote-atlanta-gt3': '"Without familiar food, I feel like a guest everywhere — all day."',
    'stat-meals': 'meals/wk',
    'stat-chinese': 'Chinese',
    'eyebrow-kitchens': 'The Kitchens',
    'gallery-title': 'Gallery of Food and Where They Come From.',
    'gallery-sub': 'The stove, the condiments, the bowls — the architecture of a life maintained.',
    'gc-la-01': 'Los Angeles · kitchen',
    'gc-la-02': 'Los Angeles · condiments',
    'gc-bos-01': 'Boston · kitchen',
    'gc-bos-02': 'Boston · condiments',
    'gc-atl-01': 'Atlanta · Home-cooked Food',
    'gc-atl-02': 'Atlanta · stove',
    'gc-atl-03': 'Atlanta · condiments',
    'gc-atl-04': 'Atlanta · kitchen',
    'gc-atl-05': 'Atlanta · spice rack',
    'gc-atl-06': 'Atlanta · 南北通 delivery',
    'gc-ith-01': 'Ithaca · kitchen',
    'gc-ith-02': 'Ithaca · cooked with care',
    'gc-cvl-01': 'Charlottesville · kitchen',
    'gc-cvl-02': 'Charlottesville · pantry',
    'gc-del-01': '南北通 · Georgia Tech delivery',
    'gc-del-02': 'Delivery · unboxed',
    'gc-del-03': 'Delivery · dropped-off',
    'eyebrow-tensions': 'What the food is really saying',
    't-section-title': 'Five Tensions',
    't-section-sub': 'These are not just eating habits. They are five recurring arguments conducted entirely through what ends up on a plate.',
    't-sub-click': 'Click to explore.',
    't1-title': 'Gut Memory',
    't1-teaser': 'No one misses "Chinese food." They miss a specific fish, a specific vendor, a specific hour of day.',
    't1-body': 'This is not nostalgia. This is the body carrying a spatial and sensory record that no substitute can overwrite. The dish missed is always particular. The grief is always particular. The person in Los Angeles doesn\'t miss Chinese food — they miss freshwater river fish, the fat of the <span class="cn">鲢鱼头</span>. The person in Ithaca doesn\'t miss Sichuan food — they miss a specific flavor profile so precisely defined that they can identify a single wrong ingredient in a bowl of <span class="cn">夫妻肺片</span>.',
    't1-v1-who': 'Los Angeles · 5 years',
    't1-v1-txt': 'The fish here — tilapia, sea bass — it tastes completely different from the river fish back home. <span class="cn">豆腐鱼、鲢鱼头</span> — I miss them so much. The ingredient itself doesn\'t exist here.',
    't1-v2-who': 'Ithaca · 6 years',
    't1-v2-txt': 'I ordered <span class="cn">夫妻肺片</span> and they added <span class="cn">麻酱</span>. That\'s wrong. It\'s a small thing. But the kind of wrong that accumulates.',
    't1-v3-who': 'Charlottesville · 5 years',
    't1-v3-txt': 'I\'ve had <span class="cn">凉皮</span> here. It\'s good. But it\'s not the <span class="cn">凉皮</span> I had on the street in Xi\'an. I can\'t explain why. It just isn\'t.',
    't2-title': 'The Kitchen as the Stable Room',
    't2-teaser': 'When everything else shifts, the stove follows a logic that is entirely your own.',
    't2-body': 'Six of eight people cook regularly. But the way they describe cooking reveals it is rarely just about efficiency. It is methodical, deliberate, often solitary — and deeply orienting. One person in Atlanta cooks every single meal. Another describes the precise sequence of heating oil, charring peppercorns, removing them before they burn. A third cooks to "recalibrate" after eating <span class="cn">白人饭</span>. The kitchen is the one place in America where the logic is entirely their own.',
    't2-v1-who': 'Atlanta · 2 years',
    't2-v1-txt': 'When I\'ve been eating <span class="cn">白人饭</span> for too long, I come home and cook. It\'s like recalibrating. Bringing myself back.',
    't2-v2-who': 'Atlanta · 5 years',
    't2-v2-txt': 'Heat the oil. Add the <span class="cn">花椒</span>. Wait until fragrant. Take them out before they turn black. Then the <span class="cn">杏鲍菇</span>. A little soy sauce. That\'s it.',
    't3-title': 'The Alone–Together Paradox',
    't3-teaser': 'Group delivery chats. Solo desk meals. Community assembles around the logistics of hunger, then disperses to eat alone.',
    't3-body': 'The delivery group chats — <span style="font-family:\'Noto Serif SC\',serif;color:var(--gold)">南北通</span>, campus WeChat groups with hundreds of members — create a strange new form of community. The act of ordering is collective; the act of eating is almost always alone. This is not a failure of community. It is a new shape of it — one that only makes sense in diaspora, where belonging is provisional and mealtimes are uncoupled from togetherness.',
    't3-v1-who': 'Charlottesville · 5 years',
    't3-v1-txt': 'If I order takeout alone, I can only get one dish. But one dish isn\'t enough variety. And two is too much food. The math of eating alone never works out.',
    't3-v2-who': 'Ithaca · 6 years',
    't3-v2-txt': 'Every Friday, a few of us would cook together. Each person made one dish. That was the happiest meal of the week — not because the food was great, but because we were all there.',
    't4-title': 'Resistance & Resignation',
    't4-teaser': 'They know the broth isn\'t the same. They order anyway. That "anyway" carries everything.',
    't4-body': 'Every choice to eat Chinese food in America is simultaneously an act of cultural insistence and an acceptance of imperfect translation. The students know the fish will be different, the spice will be wrong. They order anyway. In that "anyway" lives the refusal to let the category disappear, even when the specific thing within it cannot be fully recovered. The person in Los Angeles who saw bacon cooked in the hot pot for the first time — stunned, then gradually accepting, then eventually joyful — that arc is the entire experience of living between worlds.',
    't4-v1-who': 'Los Angeles · 5 years',
    't4-v1-txt': 'The first time I saw someone cook bacon in the hot pot, I was stunned. I\'m Sichuan — I\'d never seen that. But slowly I got used to it. And honestly? Eating together like that was the happiest thing.',
    't4-v2-who': 'Atlanta · 9 years',
    't4-v2-txt': 'I\'ve spent half my life here. But my tastes haven\'t changed. I don\'t think they will. That part of me just stayed.',
    't5-title': 'Absence as Dislocation',
    't5-teaser': 'Without familiar food, one person feels like a guest all day. Food is the mechanism for arriving.',
    't5-body': 'One person in Atlanta describes it most precisely: on days when they cannot eat the food they\'re used to, they feel like a guest — all day, everywhere, even in their own apartment. The word is <span class="cn">做客</span> — being a guest in someone else\'s home. The absence of familiar food doesn\'t just create hunger. It creates a background noise of unbelonging that makes every other task slightly harder. Food is not just fuel. It is the most reliable mechanism for arriving.',
    't5-v1-who': 'Atlanta · 5 years',
    't5-v1-txt': 'If I haven\'t eaten something I actually like that day, I feel like a guest the whole day. No moment of coming home and relaxing. That process — eating — is what puts me at ease.',
    't5-v2-who': 'Atlanta · 1 year',
    't5-v2-txt': 'Every time I eat Chinese food, I miss home a little. But I also feel like I\'ve come back to something.',
    'eyebrow-data': 'By the Numbers',
    'data-title': 'Patterns Across Eight',
    'data-sub': 'What the numbers say — and what they don\'t.',
    'd-l-1': 'students across 7 universities',
    'd-l-2': 'average years living in the US',
    'd-l-3': 'of weekly meals identified as Chinese',
    'd-l-4': 'cook Chinese food themselves regularly',
    'd-l-5': 'cite Sichuan / spicy as primary preference',
    'd-l-6': 'name Chinese food as their preferred cuisine',
    'bars-hd': 'Proportion of weekly meals identified as Chinese — sorted by years in the US',
    'bar-note-1': '1 year in the US, happens to be have had the most recent international transition',
    'bar-note-2': '9 years in the US — preference unchanged, proportion normalized',
    'bars-footnote': 'The range — 33% to 100% — tells the story of time. The person who has been here one year holds on most tightly. The person who has been here nine years has normalized. Neither is more or less Chinese than the other. They are at different points in the same negotiation.',
    'geo-hd': 'Geography & Access',
    'geo-sub': 'Where you live shapes how you eat. Access is not uniform.',
    'geo-la-desc': '1 person · 5 years',
    'geo-la-note': '"华人区不远。" Delivery services feel unnecessary. The city does the work.',
    'geo-atl-desc': '4 people · 1–9 years',
    'geo-atl-note': 'Moderate access. 南北通 and campus delivery exist but are used selectively. Cooking dominates.',
    'geo-bos-desc': '1 person · 5 years',
    'geo-bos-note': 'Campus delivery used briefly, then abandoned. "It wasn\'t that good anyway."',
    'geo-ith-cville-desc': '2 people · 5–6 years',
    'geo-ith-cville-note': 'Small cities, scarce access. Ithaca: $23 a box. Minnesota (before Charlottesville): 痛苦 — real suffering. Geography as deprivation.',
    'eyebrow-paradox': 'Central Argument',
    'para-pull': '<em>Alone.</em> Together. Not a contradiction —<br>an accurate description.',
    'para-body-1': 'The delivery group chats have hundreds of members. The coordination is collective. The eating is almost always solo. This new form — communal logistics, solitary consumption — is specific to diaspora and to this generation: enabled by WeChat, shaped by the economics of ordering alone.',
    'para-body-2': 'But the deeper paradox is this: the choice to eat Chinese food in America is simultaneously an act of cultural resistance and an act of resignation. Resistance, because it refuses to passively accept dining hall food as cultural neutrality. Resignation, because the food is always already a translation — the broth approximated, the vegetables substituted, the 麻酱 appearing uninvited. Students know this. Most describe a quiet grief about it — not dramatic homesickness, but a low hum of incompleteness that surfaces most acutely at mealtimes.',
    'vs-lbl-1': 'What is collective',
    'vs-txt-1': 'Group delivery chats. Shared WeChat orders with hundreds of members. Communal cooking on Friday nights. The social architecture of <em>obtaining</em> Chinese food together.',
    'vs-lbl-2': 'What is solitary',
    'vs-txt-2': 'Eating at a desk. One portion, alone. The structural awkwardness of ordering for one. The private kitchen of memory, closed to everyone else.',
    'para-body-3': 'The person in Ithaca\'s Friday communal cooking stands as the counter-image: what it looks like when logistics and eating collapse into a single moment. The happiest meal of the week. Not because the food was great. Because everyone was there.',
    'closing-eyebrow': 'A Final Word',
    'closing-body': 'Eight students. Five years average in the US. Seventy percent of meals still Chinese. <em>Not because they cannot eat otherwise.</em> Because the body, given the choice, reaches for what it knows. That reaching is not weakness. It is the most honest account any of these students can give of who they are — conducted not through language, not through ceremony, but through the daily, private, necessary act of eating.',
    'credits': '"Eating Alone Together" — Photo Documentary &amp; Oral Archive<br>8 interviews · 8 kitchens · ~20 photographs · 7 universities · 5 states<br>Chinese international students in the United States · 2024–2025',
    'listen-eyebrow': '完整版纪录片',
    'listen-title': '听完整的故事',
    'listen-sub': '十五分钟。八个声音。一部完整的声音纪录片。我还需要一些时间，请期待！',
    'lp-label': 'Documentary Audio',
    'lp-track-title': '《吃》— Eating Alone Together',
    'lp-track-sub': '完整版 · ~15 min · Mandarin',
    'lp-play-label': '播放',
    'xy-label': '届时请由此前往小宇宙收听',
    'lang-toggle': '中文'
  },
  zh: {
    'modal-title': '在阅读之前——请先聆听',
    'modal-body': '这部网络纪录片配有原声音乐。<br>八个声音，以普通话录制。<br><em>让它在你探索时在背景中流淌。</em>',
    'modal-play-label': '播放声音',
    'modal-skip': '静默继续 →',
    'audio-label': '吃 · 八个声音 · 普通话',
    'cover-en': '独食，共处',
    'cover-q': '对于在美国的中国留学生而言，食物如何成为维系文化身份认同、寻找归属感的方式？',
    'cover-scroll': '向下滚动',
    'eyebrow-project': '关于本项目',
    'pull-rd1': '当你越过边界，<br>身体不会忘记。<br>它依然在<em>渴望</em>某些东西。',
    'intro-p1': '八位中国留学生，八所美国大学——从亚特兰大到波士顿，从洛杉矶到伊萨卡。八间被拍摄的厨房，八段以普通话录制的声音。那个问题看似简单：<em>你吃什么？</em>',
    'intro-p2': '浮现出来的，远比食欲复杂。食物是身份认同每天被协商的地方——悄然地，实际地，饥饿地。每次购物都是一次微小的自我保全。每一顿独自烹饪的餐食，既是对曾经自我的排练，也是对正在成为之人的抉择。',
    'intro-p3': '这不是一个关于餐厅的故事。这是一个关于炉灶与自我之间那片空间的故事。',
    'intro-p4': '受访者在此将仅以他们所在的城市，以及那道无法忘怀的菜肴来为人所知。',
    'dq1-text': '"吃饭是世界上最重要的事。尤其是生病的时候——身体仍然想要中餐。那种本能不会妥协。"',
    'dq1-cite': '波士顿 · 麻省理工 · 在美5年',
    'dq2-text': '"我没有车，没有外卖。附近的中餐满足不了我的口味。那段时间真的很<em style="color:var(--ember);font-style:normal">痛苦</em>。"',
    'dq2-cite': '夏洛茨维尔 · 曾在明尼苏达 · 在美5年',
    'dq3-text': '"我点了夫妻肺片，他们加了麻酱。这是小事，但这种错误会积累。"',
    'dq3-cite': '伊萨卡 · 在美6年',
    'dq4-text': '"吃了太久白人饭之后，我就自己做饭。像是重新校准。要是能复刻出家里的味道，那就是一种成就感。"',
    'dq4-cite': '亚特兰大 · 在美2年',
    'eyebrow-introducing': '人物介绍',
    'eight-title': '八座城市。八道菜肴。八间厨房。',
    'eight-sub': '点击探索。',
    'p-open': '打开 →',
    'p-city-la': '洛杉矶 · 5年',
    'p-city-boston': '波士顿 · 5年',
    'p-city-atlanta-e': '亚特兰大 · 9年',
    'p-city-atlanta-gt1': '亚特兰大 · 1年',
    'p-city-ithaca': '伊萨卡 · 6年',
    'p-city-cville': '夏洛茨维尔 · 5年',
    'p-city-atlanta-gt2': '亚特兰大 · 2年',
    'p-city-atlanta-gt3': '亚特兰大 · 5年',
    'p-dish-en-la': '大肠豆腐鱼',
    'p-dish-en-boston': '糖醋排骨',
    'p-dish-en-atlanta-e': '兰州拉面',
    'p-dish-en-atlanta-gt1': '潮汕牛肉煲',
    'p-dish-en-ithaca': '夫妻肺片',
    'p-dish-en-cville': '凉皮（西安）',
    'p-dish-en-atlanta-gt2': '辣子鸡',
    'p-dish-en-atlanta-gt3': '臭桂鱼',
    'p-quote-la': '"大家一起吃饭，哪怕做的东西勉强算中餐，那已经是最开心的体验了。"',
    'p-quote-boston': '"生病的时候，身体还是想要中餐。那种本能不会妥协。"',
    'p-quote-atlanta-e': '"我一半的人生都在这里度过。但我的口味没有变。"',
    'p-quote-atlanta-gt1': '"每一顿都是中餐。每天我都自己做饭。"',
    'p-quote-ithaca': '"最开心的那顿饭——不是因为好吃，而是因为我们都在。"',
    'p-quote-cville': '"在明尼苏达——没有车，没有外卖。那段时间真的很痛苦。"',
    'p-quote-atlanta-gt2': '"吃了太久白人饭，我就去做饭。像是重新校准。"',
    'p-quote-atlanta-gt3': '"没有熟悉的食物，我整天都感觉像在做客。"',
    'stat-meals': '餐/周',
    'stat-chinese': '中餐比例',
    'eyebrow-kitchens': '厨房',
    'gallery-title': '食物与来处的影像集。',
    'gallery-sub': '炉灶、调料、碗碟——一种被维系的生活建筑。',
    'gc-la-01': '洛杉矶 · 厨房',
    'gc-la-02': '洛杉矶 · 调料',
    'gc-bos-01': '波士顿 · 厨房',
    'gc-bos-02': '波士顿 · 调料',
    'gc-atl-01': '亚特兰大 · 家常菜',
    'gc-atl-02': '亚特兰大 · 炉灶',
    'gc-atl-03': '亚特兰大 · 调料',
    'gc-atl-04': '亚特兰大 · 厨房',
    'gc-atl-05': '亚特兰大 · 调料架',
    'gc-atl-06': '亚特兰大 · 南北通外卖',
    'gc-ith-01': '伊萨卡 · 厨房',
    'gc-ith-02': '伊萨卡 · 用心烹饪',
    'gc-cvl-01': '夏洛茨维尔 · 厨房',
    'gc-cvl-02': '夏洛茨维尔 · 储物间',
    'gc-del-01': '南北通 · 佐治亚理工外卖',
    'gc-del-02': '外卖 · 开箱',
    'gc-del-03': '外卖 · 送达',
    'eyebrow-tensions': '食物真正表达的',
    't-section-title': '五种张力',
    't-section-sub': '这不仅仅是饮食习惯。这是五种反复上演的争论，全都通过盘子里的食物来进行。',
    't-sub-click': '点击探索。',
    't1-title': '身体的记忆',
    't1-teaser': '没有人真正想念"中国菜"。他们想念的是某种特定的鱼，某个特定的摊贩，某个特定的时刻。',
    't1-body': '这不是乡愁。这是身体携带着一份空间与感官的记忆，任何替代品都无法覆盖。所思念的菜肴永远是具体的。洛杉矶的那个人不是想念"中餐"——他们想念的是淡水河鱼，是<span class="cn">鲢鱼头</span>的那股肥美。伊萨卡的那个人想念的是精确到能辨别出一碗<span class="cn">夫妻肺片</span>里某个错误食材的那种风味。',
    't1-v1-who': '洛杉矶 · 5年',
    't1-v1-txt': '这里的鱼——罗非鱼、海鲈鱼——味道和家乡的河鱼完全不同。<span class="cn">豆腐鱼、鲢鱼头</span>——我太想念了。那种食材在这里根本不存在。',
    't1-v2-who': '伊萨卡 · 6年',
    't1-v2-txt': '我点了<span class="cn">夫妻肺片</span>，他们加了<span class="cn">麻酱</span>。不对。是小事，但这种错误会积累。',
    't1-v3-who': '夏洛茨维尔 · 5年',
    't1-v3-txt': '我在这里吃过<span class="cn">凉皮</span>。挺好的。但不是在西安街头吃的那碗<span class="cn">凉皮</span>。就是不一样。',
    't2-title': '厨房是稳定的房间',
    't2-teaser': '当一切都在变化，炉灶遵循的是一套完全属于你自己的逻辑。',
    't2-body': '八人中有六人经常自己做饭。他们描述做饭的方式揭示了这件事远不只是关于效率——它是有条不紊的，刻意的，通常是孤独的。一个人在亚特兰大每一顿饭都自己做。另一个描述了精确的流程：热油，放<span class="cn">花椒</span>，等出香味，在变黑之前捞出来。第三个在吃了太久<span class="cn">白人饭</span>后做饭来"重新校准"。厨房是在美国唯一一个逻辑完全属于自己的地方。',
    't2-v1-who': '亚特兰大 · 2年',
    't2-v1-txt': '吃了太久<span class="cn">白人饭</span>，我就回家做饭。像是重新校准。把自己带回来。',
    't2-v2-who': '亚特兰大 · 5年',
    't2-v2-txt': '热油。放<span class="cn">花椒</span>。等出香味。在变黑之前捞出来。然后放<span class="cn">杏鲍菇</span>。少许酱油。就这样。',
    't3-title': '独食与共食的悖论',
    't3-teaser': '群组外卖接龙。独自在桌边吃饭。社群在饥饿的物流中聚集，然后各自散去独自进食。',
    't3-body': '外卖群——<span style="font-family:\'Noto Serif SC\',serif;color:var(--gold)">南北通</span>、有数百成员的校园微信群——创造出一种奇特的新型社群形式。点餐的行为是集体的；进食的行为几乎总是孤独的。这不是社群的失败，而是社群的新形态——一种只在海外离散处境中才说得通的形态。',
    't3-v1-who': '夏洛茨维尔 · 5年',
    't3-v1-txt': '如果我一个人点外卖，只能点一道菜。但一道菜品种不够。两道又太多了。独自吃饭的算术永远算不平。',
    't3-v2-who': '伊萨卡 · 6年',
    't3-v2-txt': '每个星期五，我们几个人一起做饭。每个人做一道菜。那是一周里最开心的一顿——不是因为饭好吃，而是因为我们都在。',
    't4-title': '抵抗与妥协',
    't4-teaser': '他们知道那锅汤不一样。还是点了。那个"还是"里承载着一切。',
    't4-body': '在美国吃中餐的每一次选择，同时既是一种文化坚持，也是对不完美翻译的接受。学生们知道鱼会不同，辣度会不对。还是点了。在那个"还是"里，住着一种不让这个类别消失的拒绝。洛杉矶那个人第一次看到有人在火锅里涮培根——震惊，然后慢慢接受，最终变得快乐——那条弧线就是生活在两个世界之间的整个体验。',
    't4-v1-who': '洛杉矶 · 5年',
    't4-v1-txt': '第一次看到有人在火锅里涮培根，我震惊了。我是四川人——从没见过这个。但慢慢就习惯了。那样一起吃饭是最开心的事。',
    't4-v2-who': '亚特兰大 · 9年',
    't4-v2-txt': '我有一半的人生在这里度过。但我的口味没有变。我觉得也不会变了。我那部分就这么留在了那里。',
    't5-title': '缺席即离散',
    't5-teaser': '没有熟悉的食物，一个人整天都感觉像个客人。食物是抵达的机制。',
    't5-body': '亚特兰大有一个人说得最为精准：在吃不到自己习惯的食物的那些日子里，他们感觉像个客人——整天，到处，甚至在自己家里。那个词是<span class="cn">做客</span>——在别人家做客。熟悉食物的缺席不仅仅制造饥饿，还制造出一种无处归属的背景噪音。食物是最可靠的抵达机制。',
    't5-v1-who': '亚特兰大 · 5年',
    't5-v1-txt': '如果那天没吃到自己喜欢的东西，我就会整天感觉像在做客。没有回到家、松一口气的那一刻。吃饭——那个过程——才是让我放松下来的东西。',
    't5-v2-who': '亚特兰大 · 1年',
    't5-v2-txt': '每次吃中餐，我都会有一点想家。但同时也感觉回到了什么。',
    'eyebrow-data': '数字背后',
    'data-title': '八人之间的规律',
    'data-sub': '数字所言，与其未言。',
    'd-l-1': '位学生，跨越7所大学',
    'd-l-2': '平均在美居住年数',
    'd-l-3': '每周餐食被认定为中餐',
    'd-l-4': '人经常自己烹饪中餐',
    'd-l-5': '人以川菜/辣味为主要偏好',
    'd-l-6': '将中餐列为首选饮食',
    'bars-hd': '每周被认定为中餐的餐食比例——按在美年数排序',
    'bar-note-1': '在美1年，是最近发生国际迁移的人',
    'bar-note-2': '在美9年——偏好不变，比例趋于正常化',
    'bars-footnote': '从33%到100%的区间，讲述的是时间的故事。在这里待了一年的人抓得最紧。待了九年的人已经正常化。他们只是处于同一场协商的不同阶段。',
    'geo-hd': '地理与可获取性',
    'geo-sub': '你住在哪里决定了你吃什么。可获取性并不均等。',
    'geo-la-desc': '1人 · 5年',
    'geo-la-note': '"华人区不远。" 外卖服务感觉多余。这座城市代劳了。',
    'geo-atl-desc': '4人 · 1–9年',
    'geo-atl-note': '可获取性适中。南北通和校园外卖存在，但使用是有选择性的。烹饪为主。',
    'geo-bos-desc': '1人 · 5年',
    'geo-bos-note': '校园外卖短暂使用后放弃。"反正也不怎么好吃。"',
    'geo-ith-cville-desc': '2人 · 5–6年',
    'geo-ith-cville-note': '小城市，资源匮乏。伊萨卡：一盒23美元。明尼苏达：痛苦——真实的苦难。地理即剥夺。',
    'eyebrow-paradox': '核心论点',
    'para-pull': '<em>独食。</em> 共处。这不是矛盾——<br>这是准确的描述。',
    'para-body-1': '外卖群有数百名成员。协调是集体的。进食几乎总是独自一人。这种新形态——集体物流，孤独消费——是海外离散处境与这一代人特有的：由微信实现，被独自点餐的经济逻辑所塑造。',
    'para-body-2': '但更深层的悖论在于：在美国吃中餐的选择，同时既是一种文化抵抗，也是一种妥协。抵抗，因为它拒绝被动接受食堂的饭菜作为文化中立。妥协，因为那食物已然是翻译——汤底是近似的，蔬菜是替换过的，麻酱不请自来。大多数人对此有一种隐隐的遗憾，在吃饭时最为强烈地浮现。',
    'vs-lbl-1': '集体的是什么',
    'vs-txt-1': '外卖群接龙。数百人共享的微信订单。周五晚上一起做饭。<em>获取</em>中餐这件事的社会结构。',
    'vs-lbl-2': '孤独的是什么',
    'vs-txt-2': '在桌边一个人吃饭。一份，独食。独自点餐的结构性尴尬。记忆中那间私人厨房，对其他人关闭着。',
    'para-body-3': '伊萨卡那个人的周五共同烹饪，作为对立的图像存在：当物流与进食在同一时刻合而为一。一周里最开心的那顿饭。不是因为饭好吃。而是因为大家都在。',
    'closing-eyebrow': '结语',
    'closing-body': '八位学生。平均在美五年。七成的餐食仍是中餐。<em>不是因为他们无法吃其他东西。</em>而是因为身体在有选择的时候，会去拿它所熟悉的。那种伸手，不是软弱。那是这些学生能给出的关于自己是谁的最诚实的陈述——通过每天的、私密的、必要的进食之举。',
    'credits': '《吃》——影像纪录片与口述档案<br>8次访谈 · 8间厨房 · 约20张照片 · 7所大学 · 5个州<br>在美国的中国留学生 · 2024–2025',
    'listen-eyebrow': '完整版纪录片',
    'listen-title': '听完整的故事',
    'listen-sub': '十五分钟。八个声音。一部完整的声音纪录片。我还需要一些时间，请期待！',
    'lp-label': '纪录片音频',
    'lp-track-title': '《吃》— 独食，共处',
    'lp-track-sub': '完整版 · 约15分钟 · 普通话',
    'lp-play-label': '播放',
    'xy-label': '届时请由此前往小宇宙收听',
    'lang-toggle': 'English'
  }
};

window.PORTRAITS_ZH = {
  la: { city:'洛杉矶', years:'5年', stats:[{n:'21',l:'餐/周'},{n:'75%',l:'中餐比例'},{n:'5年',l:'在美年数'}], body:'<p>来自四川。她描述最想念的食物时，不说菜名，而说质地和来源——淡水鱼，大肠，美国超市根本无从替代的东西。每周21顿饭，一顿不落，大多数自己做。在洛杉矶，丰富的资源让外卖服务显得多余。</p><p>最重要的故事：第一次看到有人在火锅里涮培根。震惊——一个四川人，面对从未见过的东西。然后慢慢接受了。然后成了一种快乐。那条弧线，就是整个适应过程的缩影。</p>', dishDesc:'"这里的鱼——罗非鱼、海鲈鱼——和家乡的河鱼味道完全不同。那种河鱼的鲜，豆腐鱼、鲢鱼头的肥美——我在这里找不到。那种食材根本不存在。"', tags:['四川源','共同烹饪','杂糅性','洛杉矶资源'] },
  boston: { city:'波士顿', years:'5年', stats:[{n:'~20',l:'餐/周'},{n:'48%',l:'中餐比例'},{n:'5年',l:'在美年数'}], body:'<p>把吃饭描述为生活中最重要的事——听起来像是一种哲学立场。生病的时候，身体会绕过所有的协商，径直要中餐。这是身份认同在不经允许的情况下重新浮现的时刻。</p><p>曾在之前的住址使用过校园外卖。搬家后就没再用了。"反正也不怎么好吃"——一句小小的坦诚，比抱怨说的更多。</p>', dishDesc:'"嘲笑了它多少年，它还是最好的。有些菜配得上自己的刻板印象。"', tags:['杭帮菜','身体性身份认同','疾病作为真相时刻'] },
  'atlanta-e': { city:'亚特兰大', years:'9年', stats:[{n:'15',l:'餐/周'},{n:'33%',l:'中餐比例'},{n:'9年',l:'在美年数'}], body:'<p>在美国待得最久——9年——叙述是八人中最简洁的。在这里度过的成年时间多于其他任何地方，然而他们坚持：口味没有改变。不是因为拒绝适应，而是因为这种偏好是结构性的。西北中国菜不是一种怀旧偏好，这是一种经过审视的审美立场。</p><p>33%的中餐比例不是放弃，这是一场漫长协商的诚实结果。</p>', dishDesc:'"味道醇厚，食材简单，营养均衡。完美的一道菜。我不需要它复杂。"', tags:['9年——最长时间','西北中国菜','稳定的身份认同'] },
  'atlanta-gt1': { city:'亚特兰大', years:'1年', stats:[{n:'14',l:'餐/周'},{n:'100%',l:'中餐比例'},{n:'1年',l:'在美年数'}], body:'<p>在美国时间最短，中餐比例最高：100%。每顿饭都自己做。对做饭的描述是八人中最有条理的——先切菜，先下蒜和辣椒，牛肉最后下锅保持嫩度。这不是即兴发挥，这是对一套已知系统的执行，恰恰因为那套已知系统是少数几个完全属于自己的结构之一。</p>', dishDesc:'在美国找不到的那道菜。"潮汕牛肉——肉的新鲜，切法，那锅汤。这里没有任何东西能比得上。"', recipe:['把辣椒切块。把牛肉切薄片。','爆香辣椒和蒜末。','加香菜。然后牛肉快速下锅——速度是嫩度的关键。','微辣。简单。每天如此。'], tags:['1年——最新到来','100%中餐','四川辣','做饭作为纪律'] },
  ithaca: { city:'伊萨卡', years:'6年', stats:[{n:'14',l:'餐/周'},{n:'85%',l:'中餐比例'},{n:'6年',l:'在美年数'}], body:'<p>八人中社交视角最丰富的叙述。最重要的食物记忆不是一道菜，而是一次聚会：本科时每周的共同烹饪，每人做一道菜。觉得校园外卖太贵——一盒23美元加配送费。</p><p>关于夫妻肺片里加了麻酱的故事，细节很小，却非常精准。不是愤怒——只是准确。那种知道本身就是一种传承。</p>', dishDesc:'"四川的夫妻肺片不应该有芝麻酱。这道菜被误读了。而那种误读积累起来，就是一种隐隐的失落感。"', tags:['云南+四川','共同烹饪','不正宗作为悲伤','伊萨卡资源匮乏'] },
  cville: { city:'夏洛茨维尔', years:'5年（曾在明尼苏达）', stats:[{n:'~10',l:'餐/周'},{n:'50%',l:'中餐比例'},{n:'5年',l:'在美年数'}], body:'<p>叙述描绘了完整的弧线：在明尼苏达的食物匮乏，痛苦，逐渐适应，然后——一旦有了亚洲超市和厨房——某种解放。现在能做出曾以为只有餐厅才做得出的菜。</p><p>关于独自点外卖的结构性观察——一道菜品种不够，两道又太多——是对独自进食如何制造日常摩擦最为精准的描述。</p>', dishDesc:'"我在这里吃过凉皮。挺好的。但不是在西安街头吃的那碗凉皮。说不清楚为什么。就是不一样。"', tags:['湖南+四川+新疆','明尼苏达作为断裂','做饭作为解放','地理即可获取性'] },
  'atlanta-gt2': { city:'亚特兰大', years:'2年', stats:[{n:'14',l:'餐/周'},{n:'47%',l:'中餐比例'},{n:'2年',l:'在美年数'}], body:'<p>引入了这批访谈中最有共鸣的一个表达：白人饭——不带敌意，只是作为一个实用的类别。吃太多了，就需要重新校准。炉灶就是完成那次校准的地方。</p><p>所描述的那种满足感——复刻出童年的一种味道——是一种成就感，在那么多其他事情都不熟悉的时候尤为重要。</p>', dishDesc:'"这里的辣子鸡——能看出来辣椒没有辣度。味道不够浓。和在四川或重庆吃的完全不一样。"', recipe:['排骨焯水，加姜和料酒。煮开，撇沫。','把排骨冲干净。重新开始——新姜，新水。','炖30分钟。加玉米、白萝卜或者竹笋——随心情。','再炖30分钟。简单到可以放着不管。复杂到像家。'], tags:['四川源','白人饭作为类别','重新校准','复刻中的掌控感'] },
  'atlanta-gt3': { city:'亚特兰大', years:'5年', stats:[{n:'14',l:'餐/周'},{n:'82%',l:'中餐比例'},{n:'5年',l:'在美年数'}], body:'<p>用最精准的语言描述了离散的状态：不是思乡，不是抑郁——只是做客。到处，整天。那个词是做客——在别人家做客。解药不是一顿大餐，只是盘子里有一样熟悉的食物。</p><p>不会从佐治亚理工的私厨那里点餐——有卫生方面的顾虑。但在加州的时候经常点。区别不是服务，是有没有其他选择。</p>', dishDesc:'"我知道这里可能有。但鱼不一样，腌制的方法也不一样，有什么东西就是不对。"', recipe:['热油。放花椒——等出香味。','在变黑之前捞出来。把香味留在油里。','放切片的杏鲍菇。不停翻炒——不要完全软了。','半软半脆的时候：一点点酱油。好了。'], tags:['四川菜','做客——永久的客人','食物作为回家','精准的技法'] }
};

window.setLang = function(lang) {
  window.currentLang = lang;
  var T = TRANSLATIONS[lang] || TRANSLATIONS['en'];

  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (T[key] !== undefined) el.textContent = T[key];
  });

  document.querySelectorAll('[data-i18n-html]').forEach(function(el) {
    var key = el.getAttribute('data-i18n-html');
    if (T[key] !== undefined) el.innerHTML = T[key];
  });

  var btn = document.getElementById('lang-toggle-btn');
  if (btn) btn.textContent = T['lang-toggle'];

  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
};

window.toggleLang = function() {
  window.setLang(window.currentLang === 'en' ? 'zh' : 'en');
};
